### ISSUE TITLE
[FEATURE] Multiple light and dark themes

### ISSUE THREAD

**Issue by zzaria** [muuvmuuv/vscode-sundial#58]
**Describe the solution you'd like**

It'd be nice if you can set list of light and dark themes and every time it switches it picks a random one

**Describe alternatives you've considered**

You'd have to change it manually otherwise

**Additional context**

**Comment by muuvmuuv** [comment]
Honest question: why you really want this?

For me, this is a very edge feature and if I speak for myself is very distracting. "Random" is also very difficult to do, since nothing is really random in case of 2 or 3 options. Imagine the case where four times you "random" get theme 1, so you change it manually. After a few times, you will want to stay on one theme per cycle, IMO.

This is nothing I will implement, but if it gets enough up votes, I am open for pr's.

**Comment by zzaria** [comment]
ok then nvm
